name: Get Telegram Chat ID

on:
  workflow_dispatch:

jobs:
  get-chat-id:
    runs-on: ubuntu-latest

    steps:
      - name: Request getUpdates
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        run: |
          curl -s "https://api.telegram.org/bot${TG_BOT_TOKEN}/getUpdates"
